apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gitstep
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gitstep
    spec:
      containers:
      - name: git-api
        image: 'quay.io/koli/gitstep:{{default "latest" .Values.gitStepTag}}'
        command:
        - gitapi
        args:
        - --apiserver={{.Values.apiServerHost}}
        - --auth0-audience={{.Values.auth0Audience}}
        - --auth0-id={{.Values.auth0ID}}
        - --auth0-secret={{.Values.auth0Secret}}
        - --platform-secret={{.Values.platformSecret}}
        - --gitapi-host={{.Values.gitApiHost}}
        - --git-home={{default "/home/git" .Values.gitHome}}
        - --logtostderr
        - --tls-insecure
        ports:
        - containerPort: 8001
      - name: git-server
        image: 'quay.io/koli/gitstep:{{default "latest" .Values.gitStepTag}}'
        command:
        - gitserver
        args:
        - --apiserver={{.Values.apiServerHost}}
        - --platform-secret={{.Values.platformSecret}}
        - --gitapi-host=http://git-server.koli-system:8000
        - --git-home={{default "/home/git" .Values.gitHome}}
        - --logtostderr
        - --tls-insecure
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: koli-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: koli-controller
    spec:
      containers:
      - name: koli-controller
        image: 'quay.io/koli/koli-controller:{{default "latest" .Values.koliControllerTag}}'
        args:
        - --apiserver={{.Values.apiServerHost}}
        - --slugbuilder-image=quay.io/koli/slugbuilder:{{default "latest" .Values.slugBuilderTag}}
        - --slugrunner-image=quay.io/koli/slugrunner:{{default "latest" .Values.slugRunnerTag}}
        - --git-release-host=http://git-api.koli-system:8001
        - --cluster-name={{default "gaia" .Values.clusterName}}
        - --logtostderr
        - --tls-insecure
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kong
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: kong
        app: kong
    spec:
      containers:
      - name: kong
        image: mashape/kong:0.9.0
        env:
          - name: KONG_LOG_LEVEL
            value: info
          - name: KONG_DATABASE
            value: postgres
          - name: KONG_PG_USER
            value: kong
          - name: KONG_PG_DATABASE
            value: kong
          - name: KONG_PG_PASSWORD
            value: kong
          - name: KONG_PG_HOST
            value: postgres
          - name: KONG_DNS_RESOLVER
            value: {{default "10.0.0.10" .Values.kongDnsResolver}}
          - name: KONG_DNSMASQ
            value: "off"
          - name: KONG_ADMIN_LISTEN
            value: {{default "0.0.0.0:8001" .Values.kongAdminListen}}
        ports:
        - name: admin
          containerPort: 8001
          protocol: TCP
        - name: proxy
          containerPort: 8000
          protocol: TCP
        - name: proxy-ssl
          containerPort: 8443
          protocol: TCP
        - name: surf-tcp
          containerPort: 7946
          protocol: TCP
        - name: surf-udp
          containerPort: 7946
          protocol: UDP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kong-ingress
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kong-ingress
    spec:
      containers:
      - name: koli-controller
        image: quay.io/koli/kong-ingress:{{default "latest" .Values.kongIngressTag}}
        args:
        - --apiserver={{.Values.apiServerHost}}
        - --kong-server=http://kong-admin:8001
        - --logtostderr
        - --tls-insecure
