apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: controller
    spec:
      containers:
      - name: controller
        image: "quay.io/koli/controller:{{ .Values.imageTag }}"
        ports:
        - containerPort: 8000
        env:
        - name: PYTHONPATH
          value: /app
        - name: SYSTEM_TOKEN
          valueFrom:
            secretKeyRef:
              name: systemtoken
              key: token
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: crafter
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: crafter
    spec:
      containers:
      - name: crafter
        image: "quay.io/koli/crafter"
        ports:
        - containerPort: 8080
        env:
        - name: DEBUG
          value: 'true'
        - name: CLUSTER_ID
          value: git
        - name: BUILDER_STORAGE
          value: minio
        - name: SLUGBUILDER_IMAGE_NAME
          value: 'quay.io/koli/slugbuilder'
        - name: SLUGDEPLOYER_IMAGE_NAME
          value: 'quay.io/koli/slugdeployer'
        - name: SLUGRUNNER_IMAGE_NAME
          value: 'quay.io/koli/slugrunner'
        - name: S3_HOST
          value: objstorage.koli-system
        - name: S3_PORT
          value: '9000'
        # Will be removed in the future, needed to start the application
        - name: LOCAL_OBJECT_STORE_PATH
          value: /dummy
        # Will be removed in the future, needed to start the application
        - name: OBJECT_STORE_PATH
          value: /dummy
        - name: ACCESS_KEY
          value: 8TZRY2JRWMPT6UMXR6I5
        - name: ACCESS_SECRET_KEY
          value: gbstrOvotMMcg2sMfGUhA5a6Et/EI5ALtIHsobYk
        - name: GIT_HOME
          value: /opt
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api-router
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: api-router
    spec:
      containers:
      - name: api-router
        image: "quay.io/koli/api-router"
        ports:
        - containerPort: 80
        - containerPort: 443
