apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gitstep
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gitstep
    spec:
      containers:
      - name: git-api
        image: 'quay.io/koli/gitstep:{{.Values.images.gitstep}}'
        command:
        - gitapi
        args:
        - --apiserver={{.Values.k8s.apiserver}}
        - --auth0-audience={{.Values.platform.auth0aud}}
        - --auth0-id={{.Values.platform.auth0id}}
        - --auth0-secret={{.Values.platform.auth0secret}}
        - --platform-secret={{.Values.platform.jwtkey}}
        - --gitapi-host={{.Values.git.apihost}}
        - --git-home={{.Values.git.homepath}}
        - --logtostderr
        - --tls-insecure
        ports:
        - containerPort: 8001
      - name: git-server
        image: 'quay.io/koli/gitstep:{{.Values.images.gitstep}}'
        command:
        - gitserver
        args:
        - --apiserver={{.Values.k8s.apiserver}}
        - --platform-secret={{.Values.platform.jwtkey}}
        - --gitapi-host=http://git-server.koli-system:8000
        - --git-home={{.Values.git.homepath}}
        - --logtostderr
        - --tls-insecure
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: koli-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: koli-controller
    spec:
      containers:
      - name: koli-controller
        image: 'quay.io/koli/koli-controller:{{.Values.images.kolicontroller}}'
        args:
        - --apiserver={{.Values.k8s.apiserver}}
        - --slugbuilder-image=quay.io/koli/slugbuilder:{{.Values.images.slugbuilder}}
        - --slugrunner-image=quay.io/koli/slugrunner:{{.Values.images.slugrunner}}
        - --git-release-host=http://git-api.koli-system:8001
        - --cluster-name={{.Values.k8s.clustername}}
        - --logtostderr
        - --tls-insecure
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kong
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: kong
        app: kong
    spec:
      containers:
      - name: kong
        image: kong:0.10.0
        env:
          - name: KONG_LOG_LEVEL
            value: info
          - name: KONG_DATABASE
            value: postgres
          - name: KONG_PG_USER
            value: {{.Values.kong.db.user}}
          - name: KONG_PG_DATABASE
            value: {{.Values.kong.db.name}}
          - name: KONG_PG_PASSWORD
            value: {{.Values.kong.db.password}}
          - name: KONG_PG_HOST
            value: postgres.koli-system.{{.Values.k8s.clusterdns}}
          - name: KONG_DNS_RESOLVER
            value: {{.Values.k8s.dnsip}}
          - name: KONG_DNSMASQ
            value: "off"
          - name: KONG_ADMIN_LISTEN
            value: {{.Values.kong.adminlisten}}
        ports:
        - name: admin
          containerPort: 8001
          protocol: TCP
        - name: admin-ssl
          containerPort: 8444
          protocol: TCP
        - name: proxy
          containerPort: 8000
          protocol: TCP
        - name: proxy-ssl
          containerPort: 8443
          protocol: TCP
        - name: surf-tcp
          containerPort: 7946
          protocol: TCP
        - name: surf-udp
          containerPort: 7946
          protocol: UDP
      - name: provisoning
        image: quay.io/koli/base:0.1.0
        command:
          - /bin/bash
          - -c
          - |
            #!/bin/bash
            while true; do
              curl -s http://127.0.0.1:8001/apis >/dev/null
              if [[ !$? -eq 0 ]]; then
                echo 'Kong API is not ready yet!'
                sleep 5
                continue
              fi
              break
            done
            
            echo "Configuring Kubernetes => {{.Values.kong.bootstrap.k8sapi}}"
            curl -s -X POST http://127.0.0.1:8001/apis/ \
                --data "name=kubernetes" \
                --data "upstream_url=http://{{.Values.k8s.servicehost}}:8080" \
                --data "hosts={{.Values.kong.bootstrap.k8sapi}}" >/dev/null
            
            echo "Configuring CORS Plugin for Kubernetes"
            curl -s -X POST http://127.0.0.1:8001/apis/kubernetes/plugins \
                --data "name=cors" \
                --data "config.origin=*" \
                --data "config.methods=GET, POST, PUT, PATCH, DELETE" \
                --data "config.headers=Authorization, Accept, Accept-Version, Content-Type" \
                --data "config.max_age=3600" >/dev/null
            
            echo "Configuring Heapster => {{.Values.kong.bootstrap.heapsterapi}}"
            curl -s -X POST http://127.0.0.1:8001/apis/ \
                --data "name=heapster" \
                --data "upstream_url=http://heapster.koli-system.{{.Values.k8s.clusterdns}}" \
                --data "hosts={{.Values.kong.bootstrap.heapsterapi}}" >/dev/null
            
            echo "Configuring CORS Plugin for Heapster"
            curl -X POST http://127.0.0.1:8001/apis/heapster/plugins \
                --data "name=cors" \
                --data "config.origin=*" \
                --data "config.methods=GET, POST, PUT, PATCH, DELETE" \
                --data "config.headers=Authorization, Accept, Accept-Version, Content-Type" \
                --data "config.max_age=3600" >/dev/null
            
            echo "Configuring GIT API => {{.Values.kong.bootstrap.gitapi}}"
            curl -s -X POST http://127.0.0.1:8001/apis/ \
                --data "name=gitapi" \
                --data "upstream_url=http://git-api.koli-system.{{.Values.k8s.clusterdns}}:8001" \
                --data "hosts={{.Values.kong.bootstrap.gitapi}}" >/dev/null
            
            echo "Configuring CORS Plugin for GIT API"
            curl -X POST http://127.0.0.1:8001/apis/gitapi/plugins \
                --data "name=cors" \
                --data "config.origin=*" \
                --data "config.methods=GET, POST, PUT, PATCH, DELETE" \
                --data "config.headers=Authorization, Accept, Accept-Version, Content-Type" \
                --data "config.max_age=3600" >/dev/null

            echo "Configuring GIT Server => {{.Values.kong.bootstrap.gitserver}}"
            curl -s -X POST http://127.0.0.1:8001/apis/ \
                --data "name=gitserver" \
                --data "upstream_url=http://git-server.koli-system.{{.Values.k8s.clusterdns}}:8000" \
                --data "hosts={{.Values.kong.bootstrap.gitserver}}" >/dev/null
            
            echo "Configuring Kong Admin => {{.Values.kong.bootstrap.kongadminapi}}"
            curl -s -X POST http://127.0.0.1:8001/apis/ \
                --data "name=kongadmin" \
                --data "upstream_url=http://127.0.0.1:8001" \
                --data "hosts={{.Values.kong.bootstrap.kongadminapi}}" >/dev/null
            
            # Sleep forever
            /bin/bash -c "trap : TERM INT; sleep infinity & wait"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kong-ingress
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kong-ingress
    spec:
      containers:
      - name: koli-controller
        image: quay.io/koli/kong-ingress:{{.Values.images.kongingress}}
        args:
        - --apiserver={{.Values.k8s.apiserver}}
        - --kong-server=http://kong-admin:8001
        - --logtostderr
        - --tls-insecure
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: heapster
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: monitoring
        k8s-app: heapster
    spec:
      containers:
      - name: heapster
        image: gcr.io/google_containers/heapster-amd64:v1.3.0-beta.1
        imagePullPolicy: IfNotPresent
        command:
        - /heapster
        - --source=kubernetes:https://kubernetes.default
        - --sink=influxdb:http://monitoring-influxdb:8086
        - --historical_source=influxdb:http://monitoring-influxdb:8086
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: monitoring-grafana
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: monitoring
        k8s-app: grafana
    spec:
      containers:
      - name: grafana
        image: gcr.io/google_containers/heapster-grafana-amd64:v4.0.2
        ports:
          - containerPort: 3000
            protocol: TCP
        volumeMounts:
        - mountPath: /var
          name: grafana-storage
        env:
        - name: INFLUXDB_HOST
          value: monitoring-influxdb
        - name: GRAFANA_PORT
          value: "3000"
          # The following env variables are required to make Grafana accessible via
          # the kubernetes api-server proxy. On production clusters, we recommend
          # removing these env variables, setup auth for grafana, and expose the grafana
          # service using a LoadBalancer or a public IP.
        - name: GF_AUTH_BASIC_ENABLED
          value: "false"
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ORG_ROLE
          value: Admin
        - name: GF_SERVER_ROOT_URL
          # If you're only using the API Server proxy, set this value instead:
          # value: /api/v1/proxy/namespaces/koli-system/services/monitoring-grafana/
          value: /
      volumes:
      - name: grafana-storage
        emptyDir: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: monitoring-influxdb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: monitoring
        k8s-app: influxdb
    spec:
      containers:
      - name: influxdb
        image: gcr.io/google_containers/heapster-influxdb-amd64:v1.1.1
        volumeMounts:
        - mountPath: /data
          name: influxdb-storage
      volumes:
      - name: influxdb-storage
        emptyDir: {}