apiVersion: v1
kind: ReplicationController
metadata:
  name: postgres
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:9.6
          env:
            - name: POSTGRES_USER
              value: kong
            - name: POSTGRES_PASSWORD
              value: kong
            - name: POSTGRES_DB
              value: kong
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pg-data
      volumes:
        - name: pg-data
          emptyDir: {}
---
kind: ReplicationController
apiVersion: v1
metadata:
  name: minio
  labels:
    app: minio
spec:
  replicas: 1
  selector:
    app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      volumes:
      - name: objectstorage-keyfile
        secret:
          secretName: objectstorage-keyfile
      containers:
      - name: minio
        image: quay.io/deis/minio:v2.3.5
        command:
        - boot
        args:
        - server /home/minio/
        ports:
        - containerPort: 8082
          protocol: TCP
        volumeMounts:
        - name: objectstorage-keyfile
          readOnly: true
          mountPath: "/var/run/secrets/deis/minio/user"
        terminationMessagePath: "/dev/termination-log"
        imagePullPolicy: IfNotPresent
