apiVersion: v1
kind: Service
metadata:
  name: git-server
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: git-server
---
apiVersion: v1
kind: Service
metadata:
  name: git-server-ext
spec:
  type: NodePort
  ports:
    - name: git-external
      nodePort: 30800
      port: 30800
      targetPort: 8080
      protocol: TCP
  selector:
    app: git-server
---
apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: http
  selector:
    app: minio
---
apiVersion: v1
kind: Service
metadata:
  name: kong-proxy
spec:
  externalIPs:
  - {{.Values.kubernetesServiceHost}}
  ports:
  - name: kong-proxy
    port: 8000
    targetPort: 8000
    protocol: TCP
  - name: kong-proxy-ssl
    port: 7443
    targetPort: 7443
    protocol: TCP
  selector:
    app: kong
---
apiVersion: v1
kind: Service
metadata:
  name: kong-admin
spec:
  externalIPs:
  - {{.Values.kubernetesServiceHost}}
  ports:
  - name: kong-admin
    port: 8001
    targetPort: 8001
    protocol: TCP
  selector:
    app: kong
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
  - name: pgql
    port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app: postgres
