k8s:
  serviceip:
  servicehost:
  apiserver: 
  clustername: gaia
  clusterdns: svc.cluster.local
  dnsip: 10.0.0.10
images:
  gitstep: v0.5.0-alpha
  kolicontroller: v0.5.0-alpha
  slugbuilder: v0.2.0-beta
  slugrunner: v0.2.0-beta
  kongingress: v0.1.0-alpha
git:
  homepath: /home/git
  apihost:
platform:
  jwtkey:
  auth0aud:
  auth0id:
  auth0secret:
kong:
  adminlisten: 127.0.0.1:8001
  bootstrap:
    k8sapi: api.kolihub.io
    kongadminapi: kong-admin.kolihub.io
    heapsterapi: heapster.kolihub.io
    gitserver: git.kolihub.io
    gitapi: gitapi.kolihub.io
  db:
    name: kong
    user: kong
    password: 

