gitStepTag: v0.3.0-alpha
koliControllerTag: v0.4.0-alpha
slugBuilderTag: v0.1.0-alpha
kongIngressTag: 0.9.0
kubernetesServiceHost: 
gitStepGitHome: /home/git
clusterName: gaia
kongDnsResolver: 10.0.0.10
kongAdminListen: 0.0.0.0:8001

